disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "GodsBattle | Christian Obanaka"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01"
   logo = "img/logotransparentalt.svg"
   secondaryLogo = "img/logotransparent.svg"
   description = "Quality Tech Videos, How-To Guides, Web-Video Producer, In this blog you'll know more about the useful tutorials, how-to guides and other things. Educating people on random things. I love trading & tech, and have a passion for teaching and helping - where possible."
   copyright = "Â© 2026 Christian Obanaka ðŸš€"

 [params.author]
   name = "Christian Obanaka"
   email = "christian@godsbattle.net"
   image = "img/godsbattlelogo.webp"
   imageQuality = 96
   headline = "Community Manager and Futures Trader"
   bio = "Community Manager and Futures Trader"
   links = [ 
     { youtube = "https://youtube.com/godsbattle" },
     { envelope = "mailto:christian@godsbattle.net" },
     { instagram = "https://instagram.com/chrisgoingturbo" },
     { x-twitter = "https://x.com/chrisgoingturbo" },
     { shop = "https://selar.com/335737k1f5" }, 
   ]
