disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "GodsBattle | Quality Tech Tutorials"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logotransparent.svg"
   secondaryLogo = "img/logotransparentalt.svg"
   description = "Quality Tech Videos, How-To Guides, Web-Video Producer, In this blog you'll know more about the useful tutorials, how-to guides and other things. Educating people on random things. I love trading & tech, and have a passion for teaching and helping - where possible."
   copyright = "Â© 2026 GodsBattle"

 [params.author]
   name = "Christian Obanaka"
   email = "christian@godsbattle.net"
   image = "img/godsbattlelogo.webp"
   imageQuality = 96
   headline = "Web-Video Producer & Futures Trader"
   bio = "Web-Video Producer & Futures Trader"
   links = [ 
     { youtube = "https://youtube.com/godsbattle" },
     { email = "mailto:christian@godsbattle.net" },
     { instagram = "https://instagram.com/chrisgoingturbo" },
     { x-twitter = "https://x.com/chrisgoingturbo" },  
   ]
